export enum AuthStatus {
  EmailConflict = "The email address you entered already exists in our system.",
  FailedToCreateUser = "We were unable to create the user. Please try again later.",
  UserCreatedSuccessfully = "Your has been created successfully. An OTP has been sent to your email for verification.",
  AccountBlocked = "Your account has been blocked due to security or policy reasons.",
  EmailNotFound = "We could not find an account associated with the provided email address.",
  LoginSuccessful = "You have logged in successfully.",
  FailedToSignin = "We were unable to sign you in. Please try again later.",
  FailedToSendEmail = "There was an error sending the email. Please try again.",
  RegistrationSuccessful = "Your registration was successful. You may now log in.",
  LinkSentToEmail = "A link has been sent to your email",
  AccountNotVerified = "Your account is not verified,Please complete the signup Process",
  GoogleAuthFailed = "Google authentication Failed",
  DifferentLoginMethod = "Please try a different signin method",
  InvalidRole = "IThe role you have selected is invalid or not recognized. Please choose a valid role.",
  LogoutSuccessful = "You have successfully logged out of your account. You can log in again at any time.",
  UserIdRequired = "A valid User ID is required to proceed with this action.",
  // AllFieldsAreRequired = "Please ensure that all required fields are filled in before submitting the form.",
  IdRequired = "A valid ID is required to continue with this process.",
  InvalidId = "The ID you provided is not valid. Please check and try again.",
}