export enum AuthStatus {
  EmailConflict = "The email address you entered already exists in our system.",
  FailedToCreateUser = "We were unable to create the user. Please try again later.",
  UserCreated = "Your has been created successfully. An OTP has been sent to your email for verification.",
  AccountBlocked = "Your account has been blocked due to security or policy reasons.",
  EmailNotFound = "We could not find an account associated with the provided email address.",
  LoginSuccess = "You have logged in successfully.",
  EmailSendFailed = "There was an error sending the email. Please try again.",
  RegistrationSuccess = "Your registration was successful. You may now log in.",
  EmailSent = "A link has been sent to your email",
  AccountNotVerified = "Your account is not verified,Please complete the signup Process",
  GoogleAuthFailed = "Google authentication Failed",
  DifferentLoginMethod = "Please try a different signin method",
  InvalidRole = "IThe role you have selected is invalid or not recognized. Please choose a valid role.",
  LogoutSuccess = "You have successfully logged out of your account.",
  UserIdRequired = "valid user id is required to proceed with this action.",
  TrainerIdRequired = "valid trainer id is required to proceed with this action.",
  IdRequired = "Id is required.Please Check again",
  InvalidId = "The id you provided is not valid. Please check and try again.",
}
