export enum AppointmentStatus {
  FailedToBookSlot = "There was an issue with booking the slot. Please try again or choose a different time.",
  SlotBooked = "The slot has been successfully booked. Please wait for further confirmation.",
  SlotCurrentlyUnavailable = "The slot is currently unavailable. Please try again later",
  BookingRequestsRetrieved = "Booking requests retrieved successfully",
  BookingRequestsFetchFailed = "Failed to retrieve booking requests",
  BookingRejected = "Booking rejected successfully",
  BookingApproved = "Booking approved successfully",
  BookingSlotNotFound = "Booking slot not found",
  FailedToApproveRejectBookingStatus = "Failed to change appointment booking status",
  AppointmentsFetched  = "Appointments list retrieved successfully",
  AppointmentsFetchFailed  = "Failed to retrieve appointments list",
  AppointmentCancelledSuccessfully = "Appointment cancelled successfully",
  FailedToCancelAppointmentStatus = "Failed to cancel appointment schedule",
  FailedToFindAppointment = "Failed to find appointment data",
}
