export enum AppointmentStatus {
  FailedToBookSlot = "Failed to book slot please try again",
  SlotBookedSuccessfully = "Slot booked successfully. Please wait for confirmation",
  SlotCurrentlyUnavailable = "The slot is currently unavailable. Please try again later",
  BookingRequestsRetrievedSuccessfully = "Booking requests retrieved successfully",
  FailedToRetrieveBookingRequests = "Failed to retrieve booking requests",
  BookingRejected = "Booking rejected successfully",
  BookingApproved = "Booking approved successfully",
  BookingSlotNotFound = "Booking slot not found",
  FailedToApproveRejectBookingStatus = "Failed to change appointment booking status",
  AppointmentsListRetrievedSuccessfully = "Appointments list retrieved successfully",
  FailedToRetrieveAppointmentsList = "Failed to retrieve appointments list",
  AppointmentCancelledSuccessfully = "Appointment cancelled successfully",
  FailedToCancelAppointmentStatus = "Failed to cancel appointment schedule",
  FailedToFindAppointment = "Failed to find appointment data",
  FailedToCreateVideoCallLog = "Failed to create video call Log",
  VideoCallLogsRetrievedSuccessfully = "video call logs retrieved successfully",
  FailedToRetrieveVideoCallLogs = "Failed to retrieve video call logs",
}
