export enum HttpStatusCodes {
  OK = 200,
  Created = 201,
  BadRequest = 400,
  Unauthorized = 401,
  Forbidden = 403,
  NotFound = 404,
  InternalServerError = 500,
}

export enum HttpStatusMessages {
  UserIsSubscribed = "The current user is subscribed",
  EmailConflict = "The email address you entered already exists in our system.",
  IncorrectPassword = "The password you entered is incorrect for this user.",
  FailedToCreateUser = "We were unable to create the user. Please try again later.",
  UserCreatedSuccessfully = "Your has been created successfully. An OTP has been sent to your email for verification.",
  AccountBlocked = "Your account has been blocked due to security or policy reasons.",
  EmailNotFound = "We could not find an account associated with the provided email address.",
  LoginSuccessful = "You have logged in successfully.",
  FailedToSignin = "We were unable to sign you in. Please try again later.",
  FailedToSendEmail = "There was an error sending the email. Please try again.",
  InvalidOtp = "The OTP you entered is either invalid or has expired.",
  InternalServerError = "An internal server error occurred. Please try again later.",
  RegistrationSuccessful = "Your registration was successful. You may now log in.",
  OtpSendSuccessful = "The OTP has been resent to your email successfully.",
  AlreadyUserVerifiedByOtp = "This user has already been verified and cannot receive a new OTP.",
  LinkSentToEmail = "A link has been sent to your email",
  AccountNotVerified = "Your account is not verified,Please complete the signup Process",
  LinkExpired = "Link expired.",
  PassWordResetSuccess = "Your password has been successfully reset. You can now log in with your new password",
  GoogleAuthFailed = "Google authentication Failed",
  DifferentLoginMethod = "Please try a different signin method",
  UserList = "Users list retrieved successfully",
  failedToRetrieveUsersList = "Failed to retrieve user list",
  TrainersList = "Trainers list retrieved successfully",
  FailedToRetrieveTrainersList = "Failed to retrieve trainers list",
  BlockStatusUpdated = "Block status Updated successfully",
  FailedToUpdateBlockStatus = "Failed to update block status",
  UserIdRequired = "User id required",
  AllFieldsAreRequired = "All fields are required",
  InvalidRole = "Invalid role",
  TrainerApproved = "Trainer approved",
  TrainerRejected = "Trainer rejected",
  UserDetailsUpdated = "Profile updated successfully",
  FailedToUpdateUserDetails = "Failed to update user details",
  UserDataRetrieved = "User Details retrieved successfully",
  FailedToRetrieveUserDetails = "Failed to retrieve user details",
  IdRequired = "Id Required",
  InvalidId = "Invalid id",
  LogoutSuccessful = "Logged out successfully",
  NoRefreshToken = "No refresh token",
  InvalidRefreshToken = "Invalid refresh token",
  AccessTokenRefreshedSuccessFully = "Access Token refreshed successfully",
  InvalidAccessToken = "Invalid access token",
  NoAccessToken = "No access Token",
  FailedToHashPassword = "Failed to hash password",
  FailedToComparePassword = "Failed to compare password",
  PasswordUpdated = "Password updated successfully",
  MissingCloudinaryCredentials = "Missing required cloudinary environment variables",
  MissingJwtEnvironmentVariables = "Missing required jwt environment variables",
  FailedToUploadToCloudinary = "Failed to upload data to cloudinary",
  AuthenticationHeaderIsMissing = "Authentication header is missing",
  SubscriptionCreated = "Subscription added successfully",
  SubscriptionAlreadyExists = "Cannot made changes, subscription already exists",
  SubscriptionsListRetrieved = "Subscriptions list retrieved successfully",
  SubscriptionBlockStatusUpdated = "Subscription status updated successfully",
  EditedSuccessfully = "Changes made successfully",
  FailedToDelete= "Failed to delete",
  DeletedSuccessfully = "Deleted Successfully",
  FailedToRetrieveTrainerDetails = "Failed to retrieve trainer details",
  FailedToRetrieveTrainerWithSubscription = "Failed to retrieve trainer with subscription details",
  TrainerDetailsRetrieved = "Trainer details retrieved successfully",
  TrainersListRetrieved = "Trainer list retrieved successfully",
  SubscriptionAddedSuccessfully = "Subscription added successfully",
  FailedToRetrieveSubscriptionDetails = "Subscription not found or unavailable",
  FailedToCreateSubscriptionSession = "Failed to create subscription session",
  WebHookCredentialsMissing = "Web hook credentials are missing",
  WebHookVerificationFailed = "Webhook signature verification failed",
  SubscriptionIdAndTraineIdMissing = "Missing metadata: subscriptionId or trainerId.",
  SubscriptionListOfUserRetrievedSuccessfully = "User subscription list retrieved successfully",
  SubscriptionCancelledSuccessfully = "Your subscription has been cancelled successfully",
  InvalidSessionIdForStripe = "Invalid session id for stripe",
  SubscriptionBlockedUnavailabe = "Currently unavailable",
  FailedToCheckSubscriptionStatus = "Failed to check subscription status",


  //playlist
  PlayListCreated = "Playlist added successfully",
  PlayListEdited = "Changes made successfully",
  FailedToCreatePlayList = "Failed to create PlayList",
  PlayListsOfTrainerRetrievedSuccessfully = "Playlists of trainer retrieved successfully",
  
  //create video
  VideoUploadedSuccessfully = "Video uploaded successfully",
  VideoDataRetrievedSuccessfully = "Video data retrieved successfully",

  FailedToCreateBookingSlot = "Failed to add slot",
  SlotCreatedSuccessfully = "Booking slot added successfully",
  SlotDataRetrievedSuccessfully = "Slot data retrieved successfully",
  FailedToGetAvailableSlotData = "Failed to get available slot data",
  
  FailedToBookSlot = "Failed to book slot please try again",
  SlotBookedSuccessfully = "Slot booked successfully. Please wait for confirmation",
  SlotCurrentlyUnavailable = "The slot is currently unavailable. Please try again later",

  BookingRequestsRetrievedSuccessfully = "Booking requests retrieved successfully",
  FailedToRetrieveBookingRequests = "Failed to retrieve booking requests",
  BookingRejected = "Booking rejected successfully",
  BookingApproved = "Booking approved successfully",
  BookingSlotNotFound = "Booking slot not found",
  FailedToApproveRejectBookingStatus = "Failed to change appointment booking status",
  AppointmentsListRetrievedSuccessfully = "Appointments list retrieved successfully",
  FailedToRetrieveAppointmentsList = "Failed to retrieve appointments list",

  AppointmentCancelledSuccessfully = "Appointment cancelled successfully",
  FailedToCancelAppointmentStatus = "Failed to cancel appointment schedule",

  SlotDeletedSuccessfully = "Booking slot deleted successfully",
  FailedToDeleteSlot = "Failed to delete Slot",
  FailedToDeleteSlotAlreadyUsedForTakingAppointment = "Slot currently unavailbale, Please try again"

}
