export enum HttpStatusCodes {
  OK = 200,
  Created = 201,
  BadRequest = 400,
  Unauthorized = 401,
  Forbidden = 403,
  NotFound = 404,
  InternalServerError = 500,
}

export enum HttpStatusMessages {
  EmailConflict = "The email address you entered already exists in our system.",
  IncorrectPassword = "The password you entered is incorrect for this user.",
  FailedToCreateUser = "We were unable to create the user. Please try again later.",
  UserCreatedSuccessfully = "The user has been created successfully. An OTP has been sent to your email for verification.",
  AccountBlocked = "Your account has been blocked due to security or policy reasons.",
  EmailNotFound = "We could not find an account associated with the provided email address.",
  LoginSuccessful = "You have logged in successfully.",
  FailedToSignin = "We were unable to sign you in. Please try again later.",
  FailedToSendEmail = "There was an error sending the email. Please try again.",
  InvalidOtp = "The OTP you entered is either invalid or has expired.",
  InternalServerError = "An internal server error occurred. Please try again later.",
  RegistrationSuccessful = "Your registration was successful. You may now log in.",
  OtpSendSuccessful = "The OTP has been resent to your email successfully.",
  AlreadyUserVerifiedByOtp = "This user has already been verified and cannot receive a new OTP.",
  LinkSentToEmail = "A link has been sent to your email",
  AccountNotVerified = "Your account is not verified,Please complete the signup Process",
  LinkExpired = "Link expired.",
  PassWordResetSuccess = "Your password has been successfully reset. You can now log in with your new password",
  GoogleAuthFailed = "Google authentication Failed",
  DifferentLoginMethod = "Please try a different signin method",
  UserList = "Users list retrieved successfully",
  failedToRetrieveUsersList = "Failed to retrieve user list",
  TrainersList = "Trainers list retrieved successfully",
  FailedToRetrieveTrainersList = "Failed to retrieve trainers list",
  BlockStatusUpdated = "Block status Updated successfully",
  FailedToUpdateBlockStatus = "Failed to update block status",
  UserIdRequired = "User id required",
  AllFieldsAreRequired = "All fields are required",
  InvalidRole = "Invalid role",
  TrainerApproved = "Trainer approved",
  TrainerRejected = "Trainer rejected",
  UserDetailsUpdated = "Profile updated successfully",
  FailedToUpdateUserDetails = "Failed to update user details",
  UserDataRetrieved = "User Details retrieved successfully",
  FailedToRetrieveUserDetails = "Failed to retrieve user details",
  IdRequired = "Id Required",
  InvalidId = "Invalid id",
  LogoutSuccessful = "Logged out successfully",
  NoRefreshToken = "No refresh token",
  InvalidRefreshToken = "Invalid refresh token",
  AccessTokenRefreshedSuccessFully = "Access Token refreshed successfully",
  InvalidAccessToken = "Invalid access token",
  NoAccessToken = "No access Token",
  FailedToHashPassword = "Failed to hash password",
  FailedToComparePassword = "Failed to compare password"
}
