export enum SubscriptionStatus {
  SubscriptionCreated = "Subscription added successfully",
  SubscriptionAlreadyExists = "Cannot made changes, subscription already exists",
  SubscriptionsListRetrieved = "Subscriptions list retrieved successfully",
  SubscriptionAddedSuccessfully = "Subscription added successfully",
  FailedToRetrieveSubscriptionDetails = "Subscription not found or unavailable",
  FailedToCreateSubscriptionSession = "Failed to create subscription session",
  WebHookCredentialsMissing = "Web hook credentials are missing",
  WebHookVerificationFailed = "Webhook signature verification failed",
  SubscriptionIdAndTraineIdMissing = "Missing metadata: subscriptionId or trainerId.",
  SubscriptionListOfUserRetrievedSuccessfully = "User subscription list retrieved successfully",
  SubscriptionCancelledSuccessfully = "Your subscription has been cancelled successfully",
  InvalidSessionIdForStripe = "Invalid session id for stripe",
  SubscriptionBlockedUnavailabe = "Currently unavailable",
  FailedToCheckSubscriptionStatus = "Failed to check subscription status",
  UserIsSubscribed = "The current user is subscribed",
  SubscriptionBlockStatusUpdated = "Subscription status updated successfully",
  FailedToDeleteSubscription = "Failed to delete subscription",
  SubscriptionEditedSuccessfully = "Subscription edited successfully",
  SubscriptionDeletedSuccessfully = "Subscription deleted successfully",
  FailedToEditSubscription = "Failed to edit subscription",
}
